name:                lnums
version:             0.1.0.0
github:              "phagenlocher/haskell-bookcamp"
license:             BSD3
author:              "Philipp Hagenlocher"
maintainer:          "me@philipphagenlocher.de"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/phagenlocher/haskell-bookcamp#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  lnums-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lnums

tests:
  lnums-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lnums
